---
title: "project"
output: html_document
---

1. Downloading data

```{r include=FALSE}
library (rjson)
library(jsonlite)
library(tibble)

yelp <- fromJSON("~/3rd course/2 term/project/Saint-Petersburg_1.json")
str(yelp)
yelp_flat <- flatten(yelp)
yelp_tbl <- as_data_frame(yelp_flat)
df <- yelp_flat[!is.na(yelp_flat$tripAdvisor_link),]


drops <- c("foursquare_checkinsCount","foursquare_ratingVotes", "foursquare_userCount","open_hours.7","instagram_visitorsNumber", "tripAdvisor_link", "foursquare_rating")
df= df[ , !(names(df) %in% drops)]
df = distinct(df, title, .keep_all = TRUE)

```

2. Working hours

```{r include=FALSE}

library(tidyr)
df$open_hours.0[df$open_hours.0 == 'NULL'] <- list(c(0,0))
df$open_hours.1[df$open_hours.1 == 'NULL'] <- list(c(0,0))
df$open_hours.2[df$open_hours.2 == 'NULL'] <- list(c(0,0))
df$open_hours.3[df$open_hours.3 == 'NULL'] <- list(c(0,0))
df$open_hours.4[df$open_hours.4 == 'NULL'] <- list(c(0,0))
df$open_hours.5[df$open_hours.5 == 'NULL'] <- list(c(0,0))
df$open_hours.6[df$open_hours.6 == 'NULL'] <- list(c(0,0))
unnest_time= function(var, name1, name2) { df= df%>%
  dplyr::mutate(var = purrr::map(var, setNames, c("name1","name2"))) %>%
  unnest_wider(var)
}
df = df%>%
  dplyr::mutate(open_hours.0 = purrr::map(open_hours.0, setNames, c("open0","close0"))) %>%
  unnest_wider(open_hours.0)

df = df%>%
  dplyr::mutate(open_hours.1 = purrr::map(open_hours.1, setNames, c("open1","close1"))) %>%
  unnest_wider(open_hours.1)

df = df%>%
  dplyr::mutate(open_hours.2 = purrr::map(open_hours.2, setNames, c("open2","close2"))) %>%
  unnest_wider(open_hours.2)

df = df%>%
  dplyr::mutate(open_hours.3 = purrr::map(open_hours.3, setNames, c("open3","close3"))) %>%
  unnest_wider(open_hours.3)

df = df%>%
  dplyr::mutate(open_hours.4 = purrr::map(open_hours.4, setNames, c("open4","close4"))) %>%
  unnest_wider(open_hours.4)

df = df%>%
  dplyr::mutate(open_hours.5 = purrr::map(open_hours.5, setNames, c("open5","close5"))) %>%
  unnest_wider(open_hours.5) 

df = df%>%
  dplyr::mutate(open_hours.6 = purrr::map(open_hours.6, setNames, c("open6","close6"))) %>%
  unnest_wider(open_hours.6)

df$open0= as.integer(df$open0/100)
df$open1= as.integer(df$open1/100)
df$open2= as.integer(df$open2/100)
df$open3= as.integer(df$open3/100)
df$open4= as.integer(df$open4/100)
df$open5= as.integer(df$open5/100)
df$open6= as.integer(df$open6/100)
df$close0=as.integer(df$close0/100)
df$close1=as.integer(df$close1/100)
df$close2=as.integer(df$close2/100)
df$close3=as.integer(df$close3/100)
df$close4=as.integer(df$close4/100)
df$close5=as.integer(df$close5/100)
df$close6=as.integer(df$close6/100)
```


3. Feature Ingineering. 

```{r include=FALSE}
#Feature Ingineering 
df2 = df[df$close0 == "24",]
df$noctidial = ifelse(df$title %in% df2$title, "TRUE", "FALSE")
df$id= rownames(df)
```

```{r include=FALSE}
df$category[df$category == 'c("Museums & Libraries", "Nature & Parks")'] <- "Museums & Libraries"
df$category[df$category == 'c("Sights & Landmarks", "Nature & Parks")'] <- "Sights & Landmarks"
df$category[df$category == 'c("Sights & Landmarks", "Museums & Libraries")'] <- "Museums & Libraries"
df$category[df$category == 'c("Museums & Libraries", "Concerts & Shows")'] <- "Museums & Libraries"
df$category[df$category == 'c("Sights & Landmarks", "Concerts & Shows")'] <- "Concerts & Shows"
df$category[df$category == 'c("Sights & Landmarks", "Museums & Libraries", "Nature & Parks")'] <- "Museums & Libraries"
unique(df$category)

df$free[df$category=='Sights & Landmarks']<-1
df$free[df$category=='Museums & Libraries']<-0
df$free[df$category=='Nature & Parks']<-1
df$free[df$category=='Concerts & Shows']<-0
table(df$free)
```

4. Creating must visit places

```{r include=FALSE}
library (dplyr)

df= dplyr:: mutate(df, must_visit= df$tripAdvisor_reviewsNumber)

df= df %>% select (-tripAdvisor_reviewsNumber)

summary(df$must_visit)

approval_condition = (df$must_visit >=500)

df$must_visit = ifelse(approval_condition, "1", "0")

df$must_visit <- as.numeric(df$must_visit)

```


5.Clustering 

```{r}
library(cluster.datasets)
places = df %>% select (free, duration, title)
places$id= rownames(places)
places$duration = as.numeric(places$duration)

places$duration_15 = ifelse(places$duration == 15, "1", "0") %>% as.numeric()
places$duration_60 = ifelse(places$duration == 60, "1", "0") %>% as.numeric()
places$duration_120 = ifelse(places$duration == 120, "1", "0") %>% as.numeric()
places = places %>% select(-duration)

id = places %>% select(id, title)
id$id = as.numeric(id$id)
places = places %>% select(-title)
places$id = as.numeric(places$id)
scaled_places = as.matrix(scale(places))

place.average = hclust(dist(scaled_places), method="average")
#plot(place.average, main="Average Linkage", xlab="", sub="", cex=.9)
hclusters = cutree(place.average, k = 4)

id = inner_join(id, places)
title = id %>% na.omit()
df$id = as.numeric(df$id)
df_cluster = left_join(title, df)

df_cluster$hclust = hclusters
cluster1 = df_cluster %>% filter(hclust==1)
cluster2 = df_cluster %>% filter(hclust==2)
cluster3 = df_cluster %>% filter(hclust==3)
cluster4 = df_cluster %>% filter(hclust==4)


```


6. Downloading subway data

```{r include=FALSE}

library(readr)

library(readxl)

subway <- read_excel("~/3rd course/2 term/project/Subway.xlsx")
```

6.1. Recommendation system
```{r}
#Filters to choose cluster number
free='yes'
duration=15

if (free=='yes' & duration==15) {
  df_shiny= cluster1
}

if (duration=120) {
  df_shiny= cluster2
}

if (free=='no' & duration=15) {
  df_shiny= cluster3
}

if (free=='yes' & duration=60) {
  df_shiny= cluster4
}

#Category
if (category=="Sights & Landmarks" {
    df_shiny= df_shiny[df_shiny$category="Sights & Landmarks"]
} else if (category=="Museums & Libraries") {
    df_shiny= df_shiny[df_shiny$category="Museums & Libraries"]
} else if (category=="Concerts & Shows") {
    df_shiny= df_shiny[df_shiny$category="Concerts & Shows"]
} else if (category=="Nature & Parks") {
    df_shiny= df_shiny[df_shiny$category="Nature & Parks"]
} 

#Type
top='yes'

if (type=="yes" {
    df_shiny= df_shiny[df_shiny$must_visit=1]
} else {
  df_shiny= df_shiny[df_shiny$must_visit=0]}

#Wday and time
wday= "Sunday"
time=12  

if (wday=="Monday"  {
    df_shiny= df_shiny[time>df_shiny$open0 and time<df_shiny$close0]
} else if (wday=="Tuesday") {
    df_shiny= df_shiny[time>df_shiny$open1 and time<df_shiny$close1]
} else if (wday=="Wednesday") {
    df_shiny= df_shiny[time>df_shiny$open2 and time<df_shiny$close2]
} else if (wday=="Thursday") {
    df_shiny= df_shiny[time>df_shiny$open3 and time<df_shiny$close3]
} else if (wday=="Friday") {
    df_shiny= df_shiny[time>df_shiny$open4 and time<df_shiny$close4]
} else if (wday=="Saturday ") {
    df_shiny= df_shiny[time>df_shiny$open5 and time<df_shiny$close5]
} else if (wday=="Sunday ") {
    df_shiny= df_shiny[time>df_shiny$open6 and time<df_shiny$close6]
    

#Subway
close="yes"
subway="Parnas"


```




7. Maps plotting using leaflet plugin in OpenStreetMap

```{r}
library(leaflet)
lng= list(c(30.3061295, 30.3148))
lat= list(c(59.9341393, 59.9361))
df <- data.frame(lng=lng, lat=lat)

leaflet(df) %>%
  addTiles()  %>% 
  addMarkers(lng=30.3061295, lat=59.9341393, popup="Исакиевский собор") %>%
  addMarkers(lng=30.3148, lat=	59.9361, popup="Адмиралтейская") %>%
  addPolylines(
    lng = ~df$c.30.3061295..30.3148.,
    lat = ~df$c.59.9341393..59.9361.) #Adding route 
```

8. Randon place generator

```{r}
random= sample_n(df,1)
random
cat("Place name: ", random$title, "Adress: ", random$address, "Category: ", random$category , sep= '\n')

```
9. Distance between landmarks and subway stations

```{r}
library(geosphere)
library(readxl)

Subway <- read_excel("Subway.xlsx")

Subway$x1 = as.numeric(Subway$x1)
Subway$y1 = as.numeric(Subway$y1)

xy = cbind(c(df$lat), c(df$lng))
m = cbind(c(Subway$x1),c(Subway$y1))
distm(x = xy, y = m)
m1 = as.data.frame(m)
xy1 = as.data.frame(xy)
dis = distm(x = xy, y = m)
dis2 = as.data.frame(dis)
colnames(dis2) = Subway$`Subway station`
#фильтрация
dis3 = as.matrix(dis2)
dis3[dis3 >=2000] <- NA
dis4 = as.data.frame(dis3)
dis4$cites = yelp_flat24$title
jopa322 <- function() {
a <- readline(prompt="ВВедите станцию метро: ")
dis5 = select(dis4, c(a, "cites"))
dis5 = na.omit(dis5)
b = length(dis5$cites)
if (b == 0) {
print("Достопримечательностей нет, соррямба")
} else dis5$cites
}
jopa322() 

```
