---
title: "olimp1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

 
```


```{r}
#Подготовка данных
library(jsonlite)
library(tibble)
yelp <- fromJSON("Saint-Petersburg.json")
yelp_flat <- flatten(yelp)
yelp_tbl <- as_data_frame(yelp_flat)
df <- yelp_flat[!is.na(yelp_flat$tripAdvisor_link),]

```

```{r}

#Работа со временем
library(tidyr)
df$open_hours.0[df$open_hours.0 == 'NULL'] <- list(c(0,0))
df$open_hours.1[df$open_hours.1 == 'NULL'] <- list(c(0,0))
df$open_hours.2[df$open_hours.2 == 'NULL'] <- list(c(0,0))
df$open_hours.3[df$open_hours.3 == 'NULL'] <- list(c(0,0))
df$open_hours.4[df$open_hours.4 == 'NULL'] <- list(c(0,0))
df$open_hours.5[df$open_hours.5 == 'NULL'] <- list(c(0,0))
df$open_hours.6[df$open_hours.6 == 'NULL'] <- list(c(0,0))


unnest_time= function(var, name1, name2) { df= df%>%
  dplyr::mutate(var = purrr::map(var, setNames, c("name1","name2"))) %>%
  unnest_wider(var)
}


df = df%>%
  dplyr::mutate(open_hours.0 = purrr::map(open_hours.0, setNames, c("open0","close0"))) %>%
  unnest_wider(open_hours.0)

df = df%>%
  dplyr::mutate(open_hours.1 = purrr::map(open_hours.1, setNames, c("open1","close1"))) %>%
  unnest_wider(open_hours.1)

df = df%>%
  dplyr::mutate(open_hours.2 = purrr::map(open_hours.2, setNames, c("open2","close2"))) %>%
  unnest_wider(open_hours.2)

df = df%>%
  dplyr::mutate(open_hours.3 = purrr::map(open_hours.3, setNames, c("open3","close3"))) %>%
  unnest_wider(open_hours.3)

df = df%>%
  dplyr::mutate(open_hours.4 = purrr::map(open_hours.4, setNames, c("open4","close4"))) %>%
  unnest_wider(open_hours.4)

df = df%>%
  dplyr::mutate(open_hours.5 = purrr::map(open_hours.5, setNames, c("open5","close5"))) %>%
  unnest_wider(open_hours.5) 

df = df%>%
  dplyr::mutate(open_hours.6 = purrr::map(open_hours.6, setNames, c("open6","close6"))) %>%
  unnest_wider(open_hours.6)

df$open0= as.integer(df$open0/100)
df$open1= as.integer(df$open1/100)
df$open2= as.integer(df$open2/100)
df$open3= as.integer(df$open3/100)
df$open4= as.integer(df$open4/100)
df$open5= as.integer(df$open5/100)
df$open6= as.integer(df$open6/100)
df$close0=as.integer(df$close0/100)
df$close1=as.integer(df$close1/100)
df$close2=as.integer(df$close2/100)
df$close3=as.integer(df$close3/100)
df$close4=as.integer(df$close4/100)
df$close5=as.integer(df$close5/100)
df$close6=as.integer(df$close6/100)

```

```{r}
#Feature Ingineering 
df2 = df[df$close0 == "24",]
df$noctidial = ifelse(df$title %in% df2$title, "TRUE", "FALSE")
df$id= rownames(df)
```


```{r}
df$category[df$category == 'c("Museums & Libraries", "Nature & Parks")'] <- "Museums & Libraries"
df$category[df$category == 'c("Sights & Landmarks", "Nature & Parks")'] <- "Sights & Landmarks"
df$category[df$category == 'c("Sights & Landmarks", "Museums & Libraries")'] <- "Museums & Libraries"
df$category[df$category == 'c("Museums & Libraries", "Concerts & Shows")'] <- "Museums & Libraries"

df$category[df$category == 'c("Sights & Landmarks", "Concerts & Shows")'] <- "Concerts & Shows"
df$category[df$category == 'c("Sights & Landmarks", "Museums & Libraries", "Nature & Parks")'] <- "Museums & Libraries"

unique(df$category)

df$free[df$category=='Sights & Landmarks']<-1
df$free[df$category=='Museums & Libraries']<-0
df$free[df$category=='Nature & Parks']<-1
df$free[df$category=='Concerts & Shows']<-0
table(df$free)

```

